### ISSUE TITLE
Switch authentication to rely on Google(+) ID instead of Email

### ISSUE THREAD

**Issue by Scarygami** [GoogleDeveloperExperts/experts-app-backend#1]
In the backend we only have access to the email address of the authenticated user and not the Google+ ID, so if the email address and the Google+ ID are not from the same account there will be a mismatch and requests will be rejected.

This is a known issue with a potential (slightly dirty) workaround here:
https://code.google.com/p/googleappengine/issues/detail?id=8848#c39

Using the workaround we could use the Google+ ID to check authentication instead of the email, which would prevent the issues that some people with multiple accounts and "wrong" data in the master table have.

**Comment by Scarygami** [comment]
Might be a good idea to store the "last-auth-email" to check against in the user object to prevent the extra HTTP request in case everything is in order. I wouldn't overwrite the current email though, since this is used for communication and should be the preferred email of the users.

**Comment by SmokyBob** [comment]
:+1:
