### ISSUE TITLE
App renaming/Rebranding

### ISSUE THREAD

**Issue by Scarygami** [GoogleDeveloperExperts/experts-app-backend#10]
See https://github.com/GoogleDeveloperExperts/experts-app-web/issues/14

TODO:
Rename the API
Add new client ID `66416776373-3k5goi8hn9d5rih68t8km57iliithohb.apps.googleusercontent.com`

**Comment by patt0** [comment]
I will deploy the api with a new prefix and app version number today.

We should be able to then test / integrated it with the new front end and make the version default at the opportune time.

**Comment by SmokyBob** [comment]
:+1:
