### ISSUE TITLE
Expert Masterlist - Experts from all category

### ISSUE THREAD

**Issue by SmokyBob** [GoogleDeveloperExperts/experts-app-backend#13]
- Remove the filter to consider only Technology Experts
- Map "Descriptive" Expert category to the tag version and use it in the type column
- Area of Expertise (PG) Validation should be against PGs filtered by the Expert's category
- Email After daily job with recap by category (and no verbose list of what was unchanged)

**Comment by patt0** [comment]
Are we saying that we will change the various type values from 'active', 'administrator' and 'deleted' to 'gde', 'marketing', 'productstrategy' and 'ux_ui' ?

I am not sure what is meant by Email After ...

**Comment by SmokyBob** [comment]
Yes but still keeping deleted, admin and googlers are never configured but the web app uses the email to show the charts menu.

Last point is about the automated email sent after the gas function runs daily

**Comment by SmokyBob** [comment]
Updated the GAS script to:
- check the Expert Category is valid
- check PGs by Category
- Create Accounts as is without setting category on the account

TODOs: 
- set the Expert category on the Account object when we decided how to store this information

**Comment by SmokyBob** [comment]
All the changes to the Expert Masterlist done and pushed updated Accounts
