### ISSUE TITLE
New Expert activity tracking tag to be "experts"

### ISSUE THREAD

**Issue by SmokyBob** [GoogleDeveloperExperts/experts-app-backend#2]
Because people want to use/are using the #gde tag for non-activity-related posts check for the #gdetrack tag instead

**Comment by Scarygami** [comment]
We just have to be careful when updating the gplus tasks that we keep updating data on old activities that only have the #gde tag, and don't skip them because they don't have the #gdetrack tag.

https://github.com/GoogleDeveloperExperts/gde-app-backend/blob/master/services/update_gplus.py#L340

**Comment by patt0** [comment]
We should probably look at harvesting posts with both tags for the time being with a sunset schedule for the #gde tag, and monitor new tasks being added to confirm that the message is indeed heard by the users. One month seems like a long enough timeframe for this.

**Comment by patt0** [comment]
The new tag is to be "#experts" and have 4 categories 

#gde 
#marketing
#ProductStrategy
#UX/UI

So getting a post tracked properly will need to have the program tag, the category tag, the product group and the activity type. In combination with #3 where we define some new tag for #gde and other categories.

**Comment by Scarygami** [comment]
#ux/ui won't work as tag on Google+ (and probably other social media platforms).
It would create `<a href="...">#ux</a>/ui` in the content which would be difficult to read by the app. 

Possible options:

#ux
#ux_ui 
#uxui (weird...)

**Comment by SmokyBob** [comment]
+1 for #ux_ui

**Comment by patt0** [comment]
Until further notice we are going to harvest both #experts and #gde. When we need to cut out #gde from harvesting (if the tag does not die from natural causes) we will be able to implement a simple function to determine if the existing post have #gde and are considered in the update process.

The other four categories are implemented in the staging environment and await a concerted decision to push it to the current API so we can start tracking ... which I think could be now.
