### ISSUE TITLE
update index.yaml to allow activity masters to be retrieved ordered by date

### ISSUE THREAD

**Issue by Scarygami** [GoogleDeveloperExperts/experts-app-backend#36]
So that a request like this could work:

https://elite-firefly-737.appspot.com/_ah/api/expertstracking/v2.0/activityMaster/activityMaster?limit=100&email=expert%40gmail.com&order=-date

At the moment the frontend gets the activities in "random" order, which (lacking pagination, https://github.com/GoogleDeveloperExperts/experts-app-web/issues/171) , means that newly generated activities might not be available (especially now that all the old activities have been merged).

And even with pagination it would be better to have the newest activities loaded first.

Once the index.yaml is updated the frontend should be updated to use the order parameter.

**Comment by patt0** [comment]
Indexes are updated please update the front end to use them

@LostInBrittany @justinribeiro
